<a href="https://colab.research.google.com/github/pfabreuave/practicas_colab/blob/main/csv_sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import sqlite3

In [ ]:
df = pd.read_csv("turma25.csv")
#print(df)
conn = sqlite3.connect("turma25.db")
df.to_sql("turma25_dataset", conn, if_exists="replace")
conn.close()
dbname = 'turma25.db'
conn = sqlite3.connect(dbname)
conn
read_df=pd.read_sql("select * from turma25_dataset", conn).drop(columns=["index"])
read_df

                                  Nome  Ctrl_Proj  Vers_Git  Python  Nota_Pond
0       Andrea Graciela Sánchez Rivero     100.00     65.67   31.50  47.532187
1           Andres David Pinto Hurtado     100.00     84.11   15.00  42.405938
2       Andres Gabriel Reinoza Arteaga     100.00     76.78   95.50  90.656875
3          Antony José Linares Guevara      77.67     74.89   79.15  77.813125
4    Anyela Coromoto Arboleda Angarita      88.67     78.67   73.85  76.595000
5           Consuelo Ascanio de Balabu     100.00     92.44   93.65  93.905000
6        Daily Carolina Campos Jimenez     100.00    100.00   84.30  90.187500
7              Danilson Nunes Dos Reis     100.00     81.44   79.80  82.155000
8         Denis Omar Alayza Delgadillo     100.00     34.11    0.00  18.968438
9         Elvin Efraín Conopoy Tortoza      88.67     96.33   96.95  95.999375
10       Emmanuel Phillipe Seme Ndjeng     100.00     26.78    0.00  16.906875
11                   Francisco Alfredo       0.00      0.00    0.00   0.000000
12    Gabriela Isabel  Centeno Guevara     100.00      0.00    0.00   9.375000
13      German Ulises Guaigua Guacaran       0.00      0.00    0.00   0.000000
14                     Giselle Cordone     100.00     79.56   52.25  64.407500
15       Gonzalez Pinto Johana Joselín     100.00     60.22   40.55  51.655625
16        Handy Claude Marie Milliance       0.00      0.00    0.00   0.000000
17        Heber Oswaldo Abreu Castillo     100.00     80.44   66.00  73.248750
18    Irene Del Rosario Mejías Álvarez      77.67     47.22   50.00  51.812188
19           Jesus Pasillas Buenrostro     100.00     89.78   87.80  89.500625
20       Jhoel Marcial Gonzalez Azocar     100.00     90.67   91.95  92.344688
21           Jocelyne Botshimbo M'Pusa     100.00     86.00   87.55  88.281250
22      Jovino Esteban Guerrero Toledo     100.00     96.22   54.20  70.311875
23     Karina Madelaine Perdomo Garces     100.00     78.78   42.30  57.969375
24     Katherine Andrea Boscan Perdomo      88.67     80.44   71.35  75.530313
25       Katty Josefina Perdomo Garces      88.67     73.11   76.45  76.656250
26           Leonor Cecilia Pinto Nino       0.00      0.00    0.00   0.000000
27    Lismary Carolina Sandoval Mendez      88.67     63.89   85.85  79.938125
28      Luis Alejandro Ariza Arredondo     100.00     82.33    0.00  32.530313
29          Luis Andres Rattia Montoya     100.00     96.33   52.50  69.280313
30     Manuel Jose Rodriguez Izquierdo      44.33     33.22   36.10  36.061563
31             Marcia Joaquim Da Silva      88.67     96.22   74.95  82.218437
32                Marcos Martins Simao       0.00      0.00    0.00   0.000000
33         Maribel Colmenares De Nieto     100.00     76.78   76.15  78.563125
34     Marioxis Katiuska Macías Cuyare     100.00     75.89   84.10  73.906563
35      Markelys Alexandra Pernia Leon     100.00     73.00   89.15  76.250000
36          Michael Junior Reyes Allen     100.00     82.33   89.95  88.749063
37        Nelson Mondela Cemelus Delva       0.00      0.00    0.00   0.000000
38       Nohelimar Josefina Gil Guzman     100.00     52.89   13.70  32.812812
39                Nzagi Francisco Teca       0.00      0.00    0.00   0.000000
40        Pedro Francisco Abreu Arenas     100.00     79.56   92.35  89.470000
41  Randal Anrgenis Martinez Velasquez      33.33      3.67    0.00   4.156875
42    Rosanny Janniryth Zapata La Rosa     100.00     89.78   44.70  62.563125
43         Ruben Dario Vasquez Barreto     100.00     85.11   91.00  90.187187
44                  Rudilson Manuel Ié     100.00    100.00   67.05  79.406250
45       Sofia Valentina Rumbos Nieves     100.00    100.00   95.50  97.187500
46       Vijanti Michelle Hardeo Gómez       0.00      0.00    0.00   0.000000
47   Virginia Jannalyth Zapata La Rosa     100.00     67.44    0.00  28.342500
48                         Wenega Wama      88.67     23.11    0.00  14.812500
49                    Yahiry Celex Sam     100.00     65.56   68.55  70.657500